# Generated by Django 3.0.8 on 2020-07-30 13:29

from django.db import migrations
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photo.fields.ThumbnailImageField(upload_to='photo/%y/%m'),
        ),
    ]
